Repository zimmerman-team/rawgraphs-charts, pull requests merged in 2024-01, with the labels that each got.

#4 fix: removed some redundant dimensions
  src/echartsBubblechart/visualOptions.js
  src/echartsHeatmap/visualOptions.js
  src/echartsSunburst/dimensions.js
  src/echartsSunburst/mapping.js
  src/echartsSunburst/visualOptions.js
Labels: size/L

#6 fix: add containLabel to grid charts
  src/echartsAreastack/visualOptions.js
  src/echartsAreatimeaxis/visualOptions.js
  src/echartsBarchart/visualOptions.js
  src/echartsBubblechart/visualOptions.js
  src/echartsLinechart/visualOptions.js
  src/echartsRadarchart/visualOptions.js
  src/echartsScatterchart/visualOptions.js
Labels: size/S

#5 fix: fix bar width changing issue
  src/echartsBarchart/visualOptions.js
  src/echartsGeomap/visualOptions.js
Labels: size/S

#7 fix: remove height visualoption for geomap
  src/echartsGeomap/visualOptions.js
Labels: size/XS

#8 fix: Fix chart default dimensions, renamed variables, added palette t…
  src/echartsAreastack/visualOptions.js
  src/echartsAreatimeaxis/visualOptions.js
  src/echartsCirculargraph/visualOptions.js
  src/echartsForcegraph/visualOptions.js
  src/echartsPiechart/visualOptions.js
  src/echartsSankey/visualOptions.js
  src/echartsScatterchart/visualOptions.js
Labels: size/M

#9 fix: adjust font-family
  src/bigNumber/render.js
Labels: size/XS
